export const CartActionTypes = {
  CLEAR_CART: "CLEAR_CART",
  REMOVE_ITEM_FROM_CART: "REMOVE_ITEM_FROM_CART",
  INCREASE_AMOUNT: "INCREASE_AMOUNT",
  DECREASE_AMOUNT: "DECREASE_AMOUNT",
  GET_TOTALS: "GET_TOTALS",
  GET_TOTAL_ITEMS_AND_AMOUNT: "GET_TOTAL_ITEMS_AND_AMOUNT",
  LOADING: "LOADING",
  DISPLAY_ITEMS: "DISPLAY_ITEMS",
  TOGGLE_AMOUNT: "TOGGLE_AMOUNT",
};
